#!/bin/bash

# Raspberry Pi System Info
# Marek Chorvat 2016-11-13
#
# displays CPU speed, CPU temperature, Memory info, Who is logged, Filesystem info

MHZ=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
TEMPE=$(cat /sys/class/thermal/thermal_zone0/temp)
TEMPS=$'\xc2\xb0'C

uname -a
echo
echo CPU Speed: $(($MHZ/1000)) Mhz , CPU Temp: $(($TEMPE/1000)) $TEMPS
echo
free -oh
echo
w
echo
df -h
